### ISSUE TITLE
NEAT and NEAT-kghub-scheduler aren't found on the GCP instance

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/NEAT-kghub-scheduler#3]
The Jenkins run starts up the GCP compute instance as expected, but running commands fail because NEAT and the scheduler directories can't be found:
```
12:53:27  bash: line 0: cd: NEAT: No such file or directory
12:53:27  Connection to 146.148.56.43 closed.
[Pipeline] sh
12:53:28  + gcloud compute ssh gpgpgpuwhereareyou --zone us-central1-a --ssh-flag=-tt --command= cd NEAT-kghub-scheduler && git pull && pip install . && cd .. 
12:53:31  bash: line 0: cd: NEAT-kghub-scheduler: No such file or directory
12:53:31  Connection to 146.148.56.43 closed.
[Pipeline] echo
12:53:31  Failed while updating NEAT...
```

Possibilities:
* Working directory is not as expected
* User is not as expected
* NEAT and NEAT-kghub-scheduler not actually present

**Comment by justaddcoffee** [comment]
`gcloud compute ssh gpgpgpuwhereareyou --zone us-central1-a --ssh-flag=-tt --command= cd NEAT-kghub-scheduler && git pull && pip install . && cd .. `

I suspect both these are the problem:

```
- Working directory is not as expected
- User is not as expected

```

could you try: 

`gcloud compute ssh gpgpgpuwhereareyou --zone us-central1-a --ssh-flag=-tt --command= cd ~jtr4v/NEAT-kghub-scheduler && git pull && pip install . && cd .. `

**Comment by caufieldjh** [comment]
Trying a fix in https://github.com/Knowledge-Graph-Hub/NEAT-kghub-scheduler/commit/1e3a7638edfcc736f6e20588dd141b095f934e31

**Comment by caufieldjh** [comment]
This finds the directory but the ~~jenkinsuser~~ logged in GCP user doesn't have permissions to do a git pull there:
```
14:25:15  error: cannot open .git/FETCH_HEAD: Permission denied
```
I'm guessing the easiest solution is to manually change permissions on the NEAT and NEAT-kghub-scheduler dirs in ~jtr4v

**Comment by justaddcoffee** [comment]
Could do, although it might be better to figure out what user you are on the GCP instance, and do a git clone of NEAT and NEAT-kghub-scheduler at 
`~[whatever that user is]/NEAT`
and
`~[whatever that user is]/NEAT-kghub-scheduler`

**Comment by caufieldjh** [comment]
This one's solved - on to the next challenge.
