### ISSUE TITLE
Commands sent to gcloud compute over SSH don't use the correct Python version

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/NEAT-kghub-scheduler#5]
Our gcloud compute instance has its Tensorflow + CUDA set up through a conda environment, so we need to activate that environment to use the installed Python modules etc.
Independent of that, the default Python on the instance is 2.7.17 - this is incompatible with most of our code.
One solution is to specifically run Python as `python3.8`, but this does not happen in the conda environment, and to make matters worse, if we *are* in the conda environment, then this does not access the Tensorflow setup properly (so it can't find the GPU).

I'm working through some potential solutions here: https://superuser.com/questions/1442641/activating-conda-environment-over-ssh

**Comment by caufieldjh** [comment]
This runs properly now - I had to provide a direct path with `source ~/anaconda3/bin/activate`.

**Comment by justaddcoffee** [comment]
It might make sense to automatically load the default conda environment upon login (I think you'd just add this activate command to the jenkinsuser's bash_profile - you can look at the jtr4v user's bash profile to confirm this)

**Comment by caufieldjh** [comment]
Hrm, the `.bashrc` for jtr4v and for jenkinsuser are identical, aside from username.
Neither has a `bash_profile` though I think that only applies when the ssh connection creates a login shell.
